### ISSUE TITLE
博主你好，请问一下我运行cdn的时候出现权重不在的报错，想问问整体代码是怎么运行的。

### ISSUE THREAD

**Issue by zhanjuex** [jack139/CBLUE2#1]
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../ckpt/cmeee_plus_best_globalpointer_f1_0.66070.weights', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

这个应该是先要跑cmeee的吧，但是运行的时候发现没有split_CMeEE_train.json，想问问博主能不能提供一下权重或者这个文件。感谢您。

**Comment by jack139** [comment]
CDN目录下有README可以参考

**Comment by jack139** [comment]
close
